### ISSUE TITLE
哥哥，这里有个bug。win下直接奔溃。vim7.1

### ISSUE THREAD

**Issue by evilbinary** [hmgle/gle_vimrc#1]
哥哥，这里有个bug。win下直接奔溃。vim7.1

**Comment by hmgle** [comment]
是么? 安装 7.4 以上版本试试~

**Comment by hmgle** [comment]
@evilbinary  :grimacing: e, 好像不支持 Win

**Comment by evilbinary** [comment]
弗莱tick。恩恩。ee

**Comment by hmgle** [comment]
@evilbinary 哪里出错了? 可以贴上出错信息看看~

> 哥哥，这里有个bug。win下直接奔溃。vim7.1
