### ISSUE TITLE
vim 8.1

### ISSUE THREAD

**Issue by le011** [hmgle/gle_vimrc#2]
![Uploading image.png…]()

**Comment by le011** [comment]
![image](https://user-images.githubusercontent.com/23378591/67174888-63993480-f3f6-11e9-9a5b-85a35b171d9b.png)

**Comment by hmgle** [comment]
Can you show the output of `vim --version | grep python`? I think your vim does not include the python feature.

**Comment by hmgle** [comment]
You can reinstall vim to support the python feature:

```sh
./configure --with-features=huge --enable-multibyte --enable-rubyinterp=yes --enable-pythoninterp=dynamic --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu --enable-perlinterp=dynamic --enable-luainterp=yes --enable-gui=auto --enable-cscope --disable-netbeans --prefix=/usr/local
```

Or remove these plugs:

```diff
- Plugin 'SirVer/ultisnips'
- Plugin 'honza/vim-snippets'
```

**Comment by le011** [comment]
yes,i get it.thanks
